name: Release

on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: legau/kanon-api/app
          tag_with_ref: true
